name: circhic
channels:
    - default
dependencies:
    - python
    - pip
    - pip:
        - sphinx
        - numpy
        - scipy
        - scikit-learn
        - matplotlib
        - iced
        - pandas
        - sphinx-gallery
        - numpydoc
        - pytest
